lista_5 = [
    {"nombre": "Iron Man", "es_heroe": True},
    {"nombre": "Captain America", "es_heroe": True},
    {"nombre": "Thor", "es_heroe": True},
    {"nombre": "Hulk", "es_heroe": True},
    {"nombre": "Black Widow", "es_heroe": True},
    {"nombre": "Hawkeye", "es_heroe": True},
    {"nombre": "Spider-Man", "es_heroe": True},
    {"nombre": "Black Panther", "es_heroe": True},
    {"nombre": "Doctor Strange", "es_heroe": True},
    {"nombre": "Dr Strannnnnge", "es_heroe": True},
    {"nombre": "Captain Marvel", "es_heroe": True},
    {"nombre": "Ant-Man", "es_heroe": True},
    {"nombre": "Wasp", "es_heroe": True},
    {"nombre": "Scarlet Witch", "es_heroe": True},
    {"nombre": "Vision", "es_heroe": True},
    {"nombre": "Falcon", "es_heroe": True},
    {"nombre": "Winter Soldier", "es_heroe": True},
    {"nombre": "Star-Lord", "es_heroe": True},
    {"nombre": "Gamora", "es_heroe": True},
    {"nombre": "Groot", "es_heroe": True},
    {"nombre": "Rocket Raccoon", "es_heroe": True},
    {"nombre": "Thanos", "es_heroe": False},
    {"nombre": "Loki", "es_heroe": False},
    {"nombre": "Ultron", "es_heroe": False},
    {"nombre": "Red Skull", "es_heroe": False},
    {"nombre": "Green Goblin", "es_heroe": False},
    {"nombre": "Doctor Octopus", "es_heroe": False},
    {"nombre": "Mysterio", "es_heroe": False},
    {"nombre": "Vulture", "es_heroe": False},
    {"nombre": "Hela", "es_heroe": False},
    {"nombre": "Killmonger", "es_heroe": False},
    {"nombre": "Ego", "es_heroe": False},
    {"nombre": "Ronan", "es_heroe": False},
    {"nombre": "Malekith", "es_heroe": False},
    {"nombre": "Abomination", "es_heroe": False},
    {"nombre": "Winter Soldier Villain", "es_heroe": False}
]